[package]
name = "anyrouter-worker"
edition = "2024"
authors = ["Me0wo <public@me0wo.cc>"]

[lib]
crate-type = ["cdylib"]
path = "src/proxy.rs"

[dependencies]
worker = { version = "0.7.4" }
serde_json = { version = "1" }

[profile.release]
opt-level = "s"
lto = true
strip = true
panic = "abort"
